version: '3.8'

services:
  weatherapp-dev:
    build: .
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development

volumes:
  node_modules: