version: '3.8'

services:
   backend:
     image: example-backend
     ports:
       - 8080:8080
     environment:
       - REQUEST_ORIGIN=http://localhost:5000
       - REDIS_HOST=redis
       - POSTGRES_HOST=db
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DATABASE=postgres
     container_name: backend-example

   frontend:
     image: example-frontend
     ports:
       - 5000:5000
     environment:
       - REACT_APP_BACKEND_URL=http://localhost:8080
     container_name: frontend-example

   redis:
     image: redis:latest
     container_name: redis-example

   db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: postgres
     volumes:
       - ./database:/var/lib/postgresql/data
